import time

print('Please enter a password!')
password = raw_input()
listpassword = list(password)
guessed = 0
start = time.time()
for characters in password:
    guess = 'a'
    if guess == listpassword[guessed]:
        guessed = guessed + 1
    else:
        guess = 'A'
        if guess == listpassword[guessed]:
            guessed = guessed + 1
        else:
            guess = 'b'
            if guess == listpassword[guessed]:
                guessed = guessed + 1
            else:
                guess = 'B'
                if guess == listpassword[guessed]:
                    guessed = guessed + 1
                else:
                    guess = 'c'
                    if guess == listpassword[guessed]:
                        guessed = guessed + 1
                    else:
                        guess = 'C'
                        if guess == listpassword[guessed]:
                            guessed = guessed + 1
                        else:
                            guess = 'd'
                            if guess == listpassword[guessed]:
                                    guessed = guessed + 1
                            else:
                                guess = 'D'
                                if guess == listpassword[guessed]:
                                    guessed = guessed + 1
                                else:
                                    guess = 'e'
                                    if guess == listpassword[guessed]:
                                        guessed = guessed + 1
                                    else:
                                        guess = 'E'
                                        if guess == listpassword[guessed]:
                                            guessed = guessed + 1
                                        else:
                                            guess = 'f'
                                            if guess == listpassword[guessed]:
                                                guessed = guessed + 1
                                            else:
                                                guess = 'F'
                                                if guess == listpassword[guessed]:
                                                    guessed = guessed + 1
                                                else:
                                                    guess = 'g'
                                                    if guess == listpassword[guessed]:
                                                            guessed = guessed + 1
                                                    else:
                                                        guess = 'G'
                                                        if guess == listpassword[guessed]:
                                                            guessed = guessed + 1
                                                        else:
                                                            guess = 'h'
                                                            if guess == listpassword[guessed]:
                                                                guessed = guessed + 1
                                                            else:
                                                                guess = 'H'
                                                                if guess == listpassword[guessed]:
                                                                    guessed = guessed + 1
                                                                else:
                                                                    guess = 'i'
                                                                    if guess == listpassword[guessed]:
                                                                        guessed = guessed + 1
                                                                    else:
                                                                        guess = 'I'
                                                                        if guess == listpassword[guessed]:
                                                                            guessed = guessed + 1
                                                                        else:
                                                                            guess = 'j'
                                                                            if guess == listpassword[guessed]:
                                                                                    guessed = guessed + 1
                                                                            else:
                                                                                guess = 'J'
                                                                                if guess == listpassword[guessed]:
                                                                                    guessed = guessed + 1
                                                                                else:
                                                                                    guess = 'k'
                                                                                    if guess == listpassword[guessed]:
                                                                                        guessed = guessed + 1
                                                                                    else:
                                                                                        guess = 'K'
                                                                                        if guess == listpassword[guessed]:
                                                                                            guessed = guessed + 1
                                                                                        else:
                                                                                            guess = 'l'
                                                                                            if guess == listpassword[guessed]:
                                                                                                guessed = guessed + 1
                                                                                            else:
                                                                                                guess = 'L'
                                                                                                if guess == listpassword[guessed]:
                                                                                                    guessed = guessed + 1
                                                                                                else:
                                                                                                    guess = 'm'
                                                                                                    if guess == listpassword[guessed]:
                                                                                                            guessed = guessed + 1
                                                                                                    else:
                                                                                                        guess = 'M'
                                                                                                        if guess == listpassword[guessed]:
                                                                                                            guessed = guessed + 1
                                                                                                        else:
                                                                                                            guess = 'n'
                                                                                                            if guess == listpassword[guessed]:
                                                                                                                guessed = guessed + 1
                                                                                                            else:
                                                                                                                guess = 'N'
                                                                                                                if guess == listpassword[guessed]:
                                                                                                                    guessed = guessed + 1
                                                                                                                else:
                                                                                                                    guess = 'o'
                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                        guessed = guessed + 1
                                                                                                                    else:
                                                                                                                        guess = 'O'
                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                            guessed = guessed + 1
                                                                                                                        else:
                                                                                                                            guess = 'p'
                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                    guessed = guessed + 1
                                                                                                                            else:
                                                                                                                                guess = 'P'
                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                    guessed = guessed + 1
                                                                                                                                else:
                                                                                                                                    guess = 'q'
                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                        guessed = guessed + 1
                                                                                                                                    else:
                                                                                                                                        guess = 'Q'
                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                            guessed = guessed + 1
                                                                                                                                        else:
                                                                                                                                            guess = 'r'
                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                guessed = guessed + 1
                                                                                                                                            else:
                                                                                                                                                guess = 'R'
                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                else:
                                                                                                                                                    guess = 's'
                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                    else:
                                                                                                                                                        guess = 'S'
                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                        else:
                                                                                                                                                            guess = 't'
                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                guessed = guessed + 1
                                                                                                                                                            else:
                                                                                                                                                                guess = 'T'
                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                else:
                                                                                                                                                                    guess = 'u'
                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                    else:
                                                                                                                                                                        guess = 'U'
                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                        else:
                                                                                                                                                                            guess = 'v'
                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                            else:
                                                                                                                                                                                guess = 'V'
                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                else:
                                                                                                                                                                                    guess = 'w'
                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                                    else:
                                                                                                                                                                                        guess = 'W'
                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                        else:
                                                                                                                                                                                            guess = 'x'
                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                guessed = guessed + 1
                                                                                                                                                                                            else:
                                                                                                                                                                                                guess = 'X'
                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                else:
                                                                                                                                                                                                    guess = 'y'
                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                                                    else:
                                                                                                                                                                                                        guess = 'Y'
                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                        else:
                                                                                                                                                                                                            guess = 'z'
                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                guessed = guessed + 1
                                                                                                                                                                                                            else:
                                                                                                                                                                                                                guess = 'Z'
                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                else:
                                                                                                                                                                                                                    guess = '0'
                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                        guess = '1'
                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                            guess = '2'
                                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                guess = '3'
                                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                    guess = '4'
                                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                        guess = '5'
                                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                            guess = '6'
                                                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                guessed = guessed + 1
                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                guess = '7'
                                                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                    guess = '8'
                                                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                        guess = '9'
                                                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                            guess = '!'
                                                                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                guessed = guessed + 1
                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                guess = '@'
                                                                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                    guess = '#'
                                                                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                        guess = '$'
                                                                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                            guess = '%'
                                                                                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                guess = '^'
                                                                                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                    guess = '&'
                                                                                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                        guess = '*'
                                                                                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                            guess = '('
                                                                                                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                guessed = guessed + 1
                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                guess = ')'
                                                                                                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                    guess = '-'
                                                                                                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                        guess = '_'
                                                                                                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                            guess = '='
                                                                                                                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                guessed = guessed + 1
                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                guess = '+'
                                                                                                                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                    guess = '['
                                                                                                                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                        guess = '{'
                                                                                                                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                            guess = ']'
                                                                                                                                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                guess = '}'
                                                                                                                                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                    guess = ';'
                                                                                                                                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                        guess = ':'
                                                                                                                                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                            guess = "'"
                                                                                                                                                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                guess = '"'
                                                                                                                                                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                    guess = ','
                                                                                                                                                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                        guess = '<'
                                                                                                                                                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                            guess = '.'
                                                                                                                                                                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                                guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                guess = '>'
                                                                                                                                                                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                    guess = '/'
                                                                                                                                                                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                        guess = '?'
                                                                                                                                                                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                            guess = '\\'
                                                                                                                                                                                                                                                                                                                                                                            if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                guess = '|'
                                                                                                                                                                                                                                                                                                                                                                                if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                                                    guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                    guess = '`'
                                                                                                                                                                                                                                                                                                                                                                                    if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                                                        guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                        guess = '~'
                                                                                                                                                                                                                                                                                                                                                                                        if guess == listpassword[guessed]:
                                                                                                                                                                                                                                                                                                                                                                                            guessed = guessed + 1
                                                                                                                                                                                                                                                                                                                                                                                        else:guessed = "I didn't get that!"



                                                                                                                                                                                                
        



end = time.time()
print('Your password is ' + password + '! It took ' + str(end - start) + ' seconds to hack it!')
